### ISSUE TITLE
ERROR 1114 (HY000) at line 1268: The table 'hcv_seq_orig_data' is full

### ISSUE THREAD

**Issue by jonbra** [giffordlabcvr/HCV-GLUE#2]
Hi,
I'm getting this error when running the command `docker exec gluetools-mysql installGlueProject.sh ncbi_hcv_glue`:

`ERROR 1114 (HY000) at line 1268: The table 'hcv_seq_orig_data' is full`.

I have deleted all images and downloaded everything again. Is this error related to something on our side?

Thanks,

Jon

**Comment by robjgiff** [comment]
Hi Jon,

Apologies, I missed this completely. 

Is this problem still occurring?

Thanks,

Rob

**Comment by jonbra** [comment]
Dear Robert,

No problem. I'm not exactly sure what was the problem. But it might have been related to disk space. We have now added a routine on our server that periodically removes all docker images and the problem is not occurring.

Thanks,

Jon
