### ISSUE TITLE
ERROR: The certificate of 'hcv-glue.cvr.gla.ac.uk' is not trusted.

### ISSUE THREAD

**Issue by jonbra** [giffordlabcvr/HCV-GLUE#4]
Hi,
I recently get this error when running `docker exec gluetools-mysql installGlueProject.sh ncbi_hcv_glue`: 

```
$ docker exec gluetools-mysql installGlueProject.sh ncbi_hcv_glue
Deleting old GLUE database GLUE_TOOLS ...
Creating new GLUE database GLUE_TOOLS ...
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
Retrieving ncbi_hcv_glue.sql.gz
--2024-11-13 08:20:06--  http://hcv-glue.cvr.gla.ac.uk/hcv_glue_dbs/ncbi_hcv_glue.sql.gz
Resolving hcv-glue.cvr.gla.ac.uk (hcv-glue.cvr.gla.ac.uk)... 130.209.225.240
Connecting to hcv-glue.cvr.gla.ac.uk (hcv-glue.cvr.gla.ac.uk)|130.209.225.240|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://hcv-glue.cvr.gla.ac.uk/hcv_glue_dbs/ncbi_hcv_glue.sql.gz [following]
--2024-11-13 08:20:06--  https://hcv-glue.cvr.gla.ac.uk/hcv_glue_dbs/ncbi_hcv_glue.sql.gz
Connecting to hcv-glue.cvr.gla.ac.uk (hcv-glue.cvr.gla.ac.uk)|130.209.225.240|:443... connected.
ERROR: The certificate of 'hcv-glue.cvr.gla.ac.uk' is not trusted.
ERROR: The certificate of 'hcv-glue.cvr.gla.ac.uk' hasn't got a known issuer.
Retrieval failed
```

Is it something I can do on my side, or is it perhaps necessary to update the ca-certificates inside the container?

Thanks,

Jon

**Comment by mrubiobu** [comment]
I had the same issue with docker. I installed it following the Native Installation and downloading the jar and it worked well

Cheers, 

Marc

**Comment by jonbra** [comment]
Thanks Marc!
That makes sense and suggests that it's just the downloading of  `https://hcv-glue.cvr.gla.ac.uk/hcv_glue_dbs/ncbi_hcv_glue.sql.gz`  inside the docker container that fails...

**Comment by robjgiff** [comment]
It looks like there may be issues with the URL hcv-glue.cvr.gla.ac.uk. For security reasons, Glasgow University required updates to the OS on the VM that hosts GLUE resources, which has caused some disruptions.
Kind regards,
Rob

**Comment by jonbra** [comment]
Thanks for the information. Hopefully it will be resolved soon then.

**Comment by robjgiff** [comment]
I have updated the [cvrbioinformatics/gluetools-mysql](https://hub.docker.com/repository/docker/cvrbioinformatics/gluetools-mysql/general) image, I think the issue should be fully resolved now.

**Comment by jonbra** [comment]
Thanks! I ran a quick test and it works for me now :)
